# Generated by Django 2.2 on 2020-04-24 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_buddy_app', '0004_auto_20200424_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
    ]
